# git aliases
alias gco='git checkout'
alias gcm='git checkout master'
alias ga='git add'
alias gb='git branch'
alias gd='git diff'
alias gst='git status'
alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gl='git pull'
alias gup='git pull --rebase'
alias gupv='git pull --rebase -v'
alias glog='git log --oneline --decorate --graph'
alias gm='git merge'
alias gp='git push'
alias gst='git status'
alias gsta='git stash save'
alias gstaa='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias grbc='git rebase --continue'

export PATH="$HOME/.yarn/bin:$PATH"
export PATH="$HOME/AppData/Local/Yarn/bin:$PATH"
